# Generated by Django 3.0.4 on 2020-03-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_data_saver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvdata',
            name='age',
            field=models.IntegerField(),
        ),
    ]
