# Generated by Django 3.0.4 on 2020-03-05 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csv_data_saver', '0002_auto_20200305_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csvdata',
            options={'managed': False},
        ),
    ]
